# Trigger on changes to PRs
name: pr

env:
  REGISTRY: ghcr.io
  ORGANIZATION: onuminc
  IMAGE_NAME: runatlantis-docker

on:
  pull_request:

jobs:
  pr_build_and_publish:
    permissions:
      packages: write

    runs-on: [ubuntu-latest]
    if: github.event.pull_request.draft == false
    steps:
      - name: Login to gh
        run: git config --global url.https://${{ env.ORGANIZATION }}:${{ secrets.ACTION_CLONE_TOKEN }}@github.com/.insteadOf https://github.com/

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ORGANIZATION }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install QEMU
        uses: docker/setup-qemu-action@v1

      - name: Install Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.IMAGE_NAME }}
          tags: |
            "0.0.${{ github.event.number }}-${{ github.head_ref }}"

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v3.2.0
        with:
          file: ./Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
