name: runatlantis docker image

env:
  REGISTRY: ghcr.io
  ORGANIZATION: onuminc
  IMAGE_NAME: runatlantis-docker

on:
  push:
    branches: ["main"]
    paths:
      - Dockerfile

concurrency: docker-release-in-progress

jobs:
  build_and_create_release:
    permissions:
      contents: write
      packages: write

    runs-on: [ubuntu-latest]
    steps:
      - name: Login to gh
        run: git config --global url.https://${{ env.ORGANIZATION }}:${{ secrets.ACTION_CLONE_TOKEN }}@github.com/.insteadOf https://github.com/

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ORGANIZATION }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install QEMU
        uses: docker/setup-qemu-action@v1

      - name: Install Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.IMAGE_NAME }}
          tags: latest

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v3.2.0
        with:
          file: ./docker/Dockerfile-passbolt-cli
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
